/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '@angular/common';
import * as i2 from './spinner.component';
import * as i3 from './spinner.service';
const styles_SpinnerComponent:any[] = ([] as any[]);
export const RenderType_SpinnerComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_SpinnerComponent,data:{}});
function View_SpinnerComponent_2(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),0,'img',([] as any[]),
      [[8,'src',4]],(null as any),(null as any),(null as any),(null as any)))],(null as any),
      (_ck,_v) => {
        var _co:any = _v.component;
        const currVal_0:any = _co.loadingImage;
        _ck(_v,0,0,currVal_0);
      });
}
function View_SpinnerComponent_1(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),6,'div',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i0.ɵted((null as any),['\n      '])),(_l()(),i0.ɵand(16777216,(null as any),
      (null as any),1,(null as any),View_SpinnerComponent_2)),i0.ɵdid(16384,(null as any),
      0,i1.NgIf,[i0.ViewContainerRef,i0.TemplateRef],{ngIf:[0,'ngIf']},(null as any)),
      (_l()(),i0.ɵted((null as any),['\n      '])),i0.ɵncd((null as any),0),(_l()(),
          i0.ɵted((null as any),['\n    ']))],(_ck,_v) => {
    var _co:any = _v.component;
    const currVal_0:any = _co.loadingImage;
    _ck(_v,3,0,currVal_0);
  },(null as any));
}
export function View_SpinnerComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted((null as any),['\n    '])),(_l()(),i0.ɵand(16777216,
      (null as any),(null as any),1,(null as any),View_SpinnerComponent_1)),i0.ɵdid(16384,
      (null as any),0,i1.NgIf,[i0.ViewContainerRef,i0.TemplateRef],{ngIf:[0,'ngIf']},
      (null as any)),(_l()(),i0.ɵted((null as any),['\n  ']))],(_ck,_v) => {
    var _co:i2.SpinnerComponent = _v.component;
    const currVal_0:any = _co.show;
    _ck(_v,2,0,currVal_0);
  },(null as any));
}
export function View_SpinnerComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'spinner',([] as any[]),
      (null as any),(null as any),(null as any),View_SpinnerComponent_0,RenderType_SpinnerComponent)),
      i0.ɵdid(245760,(null as any),0,i2.SpinnerComponent,[i3.SpinnerService],(null as any),
          (null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const SpinnerComponentNgFactory:i0.ComponentFactory<i2.SpinnerComponent> = i0.ɵccf('spinner',
    i2.SpinnerComponent,View_SpinnerComponent_Host_0,{name:'name',group:'group',loadingImage:'loadingImage',
        show:'show'},{showChange:'showChange'},['*']);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovZGV2L2FuZ3VsYXItc3Bpbm5lcnMvc3JjL3NwaW5uZXIuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Q6L2Rldi9hbmd1bGFyLXNwaW5uZXJzL3NyYy9zcGlubmVyLmNvbXBvbmVudC50cyIsIm5nOi8vL0Q6L2Rldi9hbmd1bGFyLXNwaW5uZXJzL3NyYy9zcGlubmVyLmNvbXBvbmVudC50cy5TcGlubmVyQ29tcG9uZW50Lmh0bWwiLCJuZzovLy9EOi9kZXYvYW5ndWxhci1zcGlubmVycy9zcmMvc3Bpbm5lci5jb21wb25lbnQudHMuU3Bpbm5lckNvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIlxuICAgIDxkaXYgKm5nSWY9XCJzaG93XCI+XG4gICAgICA8aW1nICpuZ0lmPVwibG9hZGluZ0ltYWdlXCIgW3NyY109XCJsb2FkaW5nSW1hZ2VcIiAvPlxuICAgICAgPG5nLWNvbnRlbnQ+PC9uZy1jb250ZW50PlxuICAgIDwvZGl2PlxuICAiLCI8c3Bpbm5lcj48L3NwaW5uZXI+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7OztvQkNFTTtNQUFBOzs7UUFBMEI7UUFBMUIsV0FBMEIsU0FBMUI7Ozs7b0JBREY7TUFBQSx3RUFBa0I7YUFBQSw4QkFDaEI7TUFBQSwrREFBQTtNQUFBO01BQWlELG9EQUNqRCxrQkFBeUI7aUJBQUE7O0lBRHBCO0lBQUwsV0FBSyxTQUFMOzs7O29CQUZOLDJDQUNJO01BQUEsNkVBQUE7TUFBQTtNQUFBLGVBR007O0lBSEQ7SUFBTCxXQUFLLFNBQUw7Ozs7b0JDREo7TUFBQTthQUFBO1VBQUE7SUFBQTs7Ozs7In0=
